from pathlib import Path
import html,json,re

ROOT=Path("/Users/aaron/Projects/vantalabs-site")
G=ROOT/"guardian"
SM=ROOT/"sitemap.xml"
SITE="https://vantalabs.co.uk"

PAGES=[
("school-departure-notification-app","School Departure Notification App","Know when the connected child phone leaves School","Get a useful School departure alert when the journey home begins, without repeatedly checking a map.","For many families, the useful moment is not seeing every movement during the school day but knowing when the journey home has actually started. Guardian can use a configured School safe zone to recognise when the connected child phone leaves that familiar area and provide a departure update to trusted adults.","A School departure notification is still based on phone location rather than perfect physical proof. GPS drift, buildings, signal, permissions, battery settings and background restrictions can affect timing. Parents can use the Family Map, battery level and last-update time for extra context when an alert seems unusual."),
("child-home-arrival-alert-app","Child Home Arrival Alert App","A simple alert when the child phone reaches Home","Receive a Home arrival update when a connected child phone reaches its configured Home safe zone.","A Home arrival alert can answer one ordinary question without another message or phone call: did the journey finish? Guardian lets a family create a Home safe zone so trusted adults can receive an update when the connected child device genuinely arrives inside that familiar area.","The alert is intended as practical family context rather than exact proof of somebody's position. Location accuracy can vary around buildings and roads, while signal, permissions and battery behaviour can delay updates. If something does not look right, direct family contact remains more important than the app."),
("after-school-location-app","After School Location App","Useful location context for the journey after School","Use Guardian for useful after-school location context, School departure alerts and Home arrival updates.","The period after School is often when parents want the most useful context with the least amount of monitoring. A School departure alert can show that the journey has begun, while a Home safe-zone update can show when the connected child phone reaches home. The Family Map is there when a closer look is genuinely useful.","Guardian does not promise uninterrupted tracking between those milestones. Phone location can change with signal, buildings, permissions, battery saving and operating-system restrictions. The latest location, battery status and last-update time should be read together rather than treated as minute-by-minute surveillance."),
("walking-to-school-safety-app","Walking to School Safety App","Support independent school journeys with useful alerts","Use Home and School alerts to support children who walk to School without watching their location continuously.","When a child begins walking to School independently, families often want reassurance around a few agreed moments rather than constant observation. Guardian can provide a Home departure update, a School arrival alert and access to the latest available Family Map location when extra context is needed.","That approach leaves room for independence while keeping trusted adults informed about familiar milestones. GPS and notification delivery can still be affected by the phone, network and surroundings, so Guardian should support family communication rather than replace it. In immediate danger, contact the child and emergency services directly."),
("child-journey-alerts-app","Child Journey Alerts App","Location alerts around everyday child journeys","Use familiar-place alerts for routine journeys between Home, School and other agreed safe zones.","A child journey usually matters most at the beginning and end: leaving a familiar place, reaching the destination and knowing when the expected routine changes. Guardian safe zones can turn those moments into useful family notifications without requiring a parent to keep the Family Map open throughout the journey.","Families can use the latest available location and device status when an alert needs more context. The information is dependent on the connected phone and can be affected by GPS conditions, signal, permissions, battery settings and background restrictions. It should be treated as helpful context rather than a guarantee."),
("child-device-battery-status-app","Child Device Battery Status App","See battery context alongside a child's latest location","Check the connected child phone's battery level and last-update time alongside Guardian location information.","A location dot means more when parents can also understand what the phone is reporting. Guardian shows useful device context such as battery level and the time of the latest update, helping a trusted adult distinguish a recent report from information that may be getting older.","Low battery, disabled permissions, connectivity problems and operating-system restrictions can all affect background location updates. Battery status does not diagnose every problem, but it gives families another practical clue before they assume that an older location means something has gone wrong."),
("child-phone-last-location-app","Child Phone Last Location App","Check the latest available location from a connected child phone","See a child's latest available shared location together with last-update and battery context.","Guardian is designed around the latest location that the connected child phone has successfully shared, not a promise that the map is continuously live every second. Parents can open the Family Map to see that available position and use the last-update time to understand how recent it is.","This distinction matters when a phone loses signal, enters a building, restricts background activity or runs low on battery. The last available location can provide useful context, but it should never be treated as proof of the child's current position when the update is old or circumstances are unusual."),
("child-location-not-updating-app","Child Location Not Updating App","Understand why a child location may stop updating","Check battery, signal, permissions and background settings when a connected child phone stops reporting location.","A location that has not changed for a while does not automatically mean the child has stayed in the same place. The connected phone may have weak signal, restricted background activity, low battery or a permissions problem. Guardian's battery and last-update information can help parents work through those practical possibilities.","Start by checking how old the latest report is, whether the phone appears to have battery power and whether normal family contact is available. Buildings and GPS conditions can also affect location. Guardian provides context for troubleshooting but cannot remotely guarantee that a phone will continue reporting."),
("family-location-app-with-safe-zones","Family Location App With Safe Zones","Private family location with useful safe-zone alerts","Combine a private Family Map with Home, School and familiar-place alerts in Guardian.","A family location app becomes more useful when parents do not need to open the map for every routine journey. Guardian safe zones allow trusted adults to define familiar places and receive arrival or leaving updates around those agreed locations while keeping the Family Map available for occasional context.","Safe zones rely on phone location, so boundaries should allow for normal GPS variation around buildings, roads and entrances. Families should test the routine and use sensible zone sizes rather than expecting exact doorway-level detection. Location sharing remains inside the private, parent-managed family."),
("family-location-app-with-sos","Family Location App With SOS","Family location tools with an SOS route to trusted adults","Guardian combines private family location, safe-zone alerts and an SOS option on the connected child device.","Most everyday Guardian use is about routine reassurance: Home and School alerts, the latest available Family Map location and device context. The connected child device also has an SOS option that provides another route for contacting trusted adults when the child wants help or attention.","An SOS feature does not turn Guardian into an emergency service and delivery can still depend on connectivity, permissions and device conditions. Families should agree in advance who responds to an SOS and what happens next. If somebody may be in immediate danger, contact emergency services directly."),
("parent-location-sharing-app","Parent Location Sharing App","Optional location sharing for parents inside the family","Adults can choose whether to share their own location with trusted family members in Guardian.","Family location sharing does not need to mean that every adult is permanently visible. Guardian keeps parent location sharing optional, allowing adults to decide whether sharing their own location is useful for the family's routine while child-device safety features remain focused on the connected child profile.","That choice matters for privacy and healthy boundaries. Families should discuss who can see location information, why it is being shared and when it is useful. Guardian keeps access within the private family rather than creating public profiles or a social-location feed."),
("co-parent-location-sharing-app","Co-Parent Location Sharing App","Useful child location updates for trusted co-parents","Share Guardian family access with another trusted parent so both can receive useful child safety context.","Co-parenting can make simple journey updates harder when a child moves between homes, school and other familiar places. Guardian can give trusted parents access to the same private family context, including safe-zone alerts and the latest available child-device location, without requiring public sharing.","Access should stay limited to adults who genuinely need it, and the family should agree how location information will be used. Guardian provides practical context around routines; it is not designed as evidence for disputes, hidden surveillance or a replacement for direct communication between parents."),
("family-location-app-without-social-feed","Family Location App Without a Social Feed","Family location sharing without followers, feeds or social noise","Guardian keeps family location tools private and focused, without turning safety information into a social network.","Some families want location alerts and a private map without profiles, followers, public posts or another stream of social features. Guardian is deliberately centred on the family itself: trusted access, familiar-place alerts, recent location context, device status and SOS tools.","Keeping the product focused does not remove the need for healthy boundaries. Families should still discuss what is shared and why. Phone location also has practical limits, so the map and alerts should be used proportionately rather than as a reason to monitor every movement."),
("private-family-location-app-iphone-android","Private Family Location App for iPhone and Android","Private family location across iPhone and Android","Use Guardian across supported iPhone and Android devices with private family access and useful location alerts.","Families often use a mix of phones rather than one platform. Guardian is available through the App Store and Google Play so supported iPhone and Android devices can take part in the same family safety routine, subject to the permissions and background-location behaviour of each device.","Platform settings can affect how reliably a phone reports in the background, so location permissions, battery optimisation and connectivity still matter. Guardian keeps the resulting family information private to authorised family members and provides last-update context when a device has not reported recently.")
]

def e(x): return html.escape(x,quote=True)

for slug,name,h1,desc,p1,p2 in PAGES:
    url=f"{SITE}/guardian/{slug}/"
    faqs=[
        (f"What is {name.lower()} used for?",desc),
        ("Can phone settings affect Guardian location updates?","Yes. GPS, connectivity, permissions, battery settings and operating-system restrictions can affect location reporting and notification timing."),
        ("Is Guardian an emergency service?","No. Guardian provides family location and alert context. In immediate danger, contact the emergency services directly.")
    ]
    schema=json.dumps([
        {"@context":"https://schema.org","@type":"SoftwareApplication","name":"Guardian: Family Tracker","applicationCategory":"LifestyleApplication","operatingSystem":"Android, iOS","description":desc,"url":url,"image":SITE+"/guardian.png","publisher":{"@type":"Organization","name":"Vanta Labs","url":SITE+"/"}},
        {"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":q,"acceptedAnswer":{"@type":"Answer","text":a}} for q,a in faqs]}
    ],ensure_ascii=False)

    faq="".join(f"<details><summary>{e(q)}</summary><p>{e(a)}</p></details>" for q,a in faqs)

    page=f'''<!doctype html><html lang="en-GB"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{e(name)} | Guardian by Vanta Labs</title>
<meta name="description" content="{e(desc)}">
<link rel="canonical" href="{url}">
<meta name="robots" content="index,follow,max-image-preview:large">
<meta property="og:type" content="website"><meta property="og:site_name" content="Vanta Labs">
<meta property="og:title" content="{e(name)} | Guardian by Vanta Labs">
<meta property="og:description" content="{e(desc)}"><meta property="og:url" content="{url}">
<meta property="og:image" content="{SITE}/guardian.png"><meta name="twitter:card" content="summary_large_image">
<link rel="icon" href="/guardian.png"><link rel="stylesheet" href="/guardian/assets/guardian.css">
<script defer src="/guardian/assets/app-links.js"></script>
<script type="application/ld+json">{schema}</script></head>
<body class="guardian-detail guardian-seo-page">
<header class="head"><nav><a class="brand" href="/">Vanta Labs</a><div class="links"><a href="/guardian/">Guardian</a><a href="/guardian/features/">Features</a><a href="/guardian/guides/what-is-a-family-safety-app/">Guides</a><a href="/">All apps</a></div></nav></header>
<main><section class="hero"><div><div class="eyebrow">Family safety and location</div><h1>{e(h1)}</h1><p class="lead">{e(desc)}</p><div class="ctas"><a class="btn" data-store="ios">App Store</a><a class="btn alt" data-store="android">Google Play</a></div></div><div class="iconbox"><img src="/guardian.png" alt="Guardian family tracker app icon" width="512" height="512"></div></section>
<article class="body"><section class="long-copy"><h2>{e(name)}, built around useful family context</h2><div class="long-copy-text"><p>{e(p1)}</p><p>{e(p2)}</p></div></section><div class="notice"><strong>Guardian is not an emergency service.</strong> Location and notifications can be affected by GPS, connectivity, permissions, battery settings and operating-system restrictions.</div></article>
<div class="guardian-lower-grid"><section class="related"><h2>Keep exploring Guardian</h2><div class="grid"><a class="card" href="/guardian/child-location-app/"><strong>Child Location App</strong></a><a class="card" href="/guardian/safe-zone-alerts-app/"><strong>Safe Zone Alerts App</strong></a><a class="card" href="/guardian/family-map-app/"><strong>Family Map App</strong></a></div></section><section class="faq"><h2>Quick questions</h2>{faq}</section></div></main>
<footer><div><span>© 2026 Vanta Labs NW LTD</span><span><a href="/privacy.html">Privacy</a> · <a href="/terms.html">Terms</a> · <a href="/">All Vanta Labs apps</a></span></div></footer></body></html>'''

    d=G/slug
    d.mkdir(parents=True,exist_ok=True)
    (d/"index.html").write_text(page)

# Canonical hostname consistency on all Guardian HTML.
for path in G.rglob("*.html"):
    text=path.read_text()
    text=text.replace("https://www.vantalabs.co.uk","https://vantalabs.co.uk")
    path.write_text(text)

# Guardian URLs in root sitemap use the same canonical host.
sm=SM.read_text()
sm=sm.replace("https://www.vantalabs.co.uk/guardian","https://vantalabs.co.uk/guardian")

for slug,*_ in PAGES:
    url=f"{SITE}/guardian/{slug}/"
    if f"<loc>{url}</loc>" not in sm:
        sm=sm.replace("</urlset>",f'  <url><loc>{url}</loc><changefreq>monthly</changefreq><priority>0.75</priority></url>\n</urlset>')

SM.write_text(sm)
print("GUARDIAN PAGES:",len(list(G.rglob("index.html"))))
